stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t your_image_name:latest .

deploy:
  stage: deploy
  image: python:3.8
  before_script:
    - pip install ansible
  script:
    - ansible-playbook -i ansible/hosts ansible/deploy.yml
  only:
    - feat/ansible
